<a href="https://www.kaggle.com/code/nasratullahshafiq/gas-emition-in-climate-change?scriptVersionId=210389062" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/co-and-greenhouse-gas-emissions/2- annual-co-emissions-by-region.csv
/kaggle/input/co-and-greenhouse-gas-emissions/3- co-emissions-per-capita.csv
/kaggle/input/co-and-greenhouse-gas-emissions/1- temperature-anomaly.csv

In [2]:
annual_df = pd.read_csv('/kaggle/input/co-and-greenhouse-gas-emissions/2- annual-co-emissions-by-region.csv')

In [3]:
annual_df.sample(5)

             Entity Code  Year  Annual CO₂ emissions
24533     Singapore  SGP  1960          1.392320e+06
9130   Europe (GCP)  NaN  2001          6.282255e+09
3090        Bahrain  BHR  2003          1.676949e+07
6403        Comoros  COM  1989          5.129600e+04
11523        Greece  GRC  1989          7.323081e+07

In [4]:
annual1_df = pd.read_csv('/kaggle/input/co-and-greenhouse-gas-emissions/3- co-emissions-per-capita.csv')

In [5]:
annual1_df.sample(5)

             Entity Code  Year  Annual CO₂ emissions (per capita)
1161        Armenia  ARM  1978                           2.425144
4414   Burkina Faso  BFA  1996                           0.066348
1856      Australia  AUS  1914                           5.327880
12059       Ireland  IRL  1933                           3.208025
11235     Hong Kong  HKG  1993                           5.710827

In [6]:
annual2_df = pd.read_csv('/kaggle/input/co-and-greenhouse-gas-emissions/1- temperature-anomaly.csv')

In [7]:
annual2_df.sample(5)

,Entity,Code,Year,Global average temperature anomaly relative to 1961-1990,Upper bound of the annual temperature anomaly (95% confidence interval),Lower bound of the annual temperature anomaly (95% confidence interval)
140,Global,NaN,1990,0.360562,0.396573,0.324552
381,Southern hemisphere,NaN,1883,-0.265885,-0.134847,-0.396924
199,Northern hemisphere,NaN,1875,-0.483722,-0.287447,-0.679998
378,Southern hemisphere,NaN,1880,-0.247666,-0.107117,-0.388216
434,Southern hemisphere,NaN,1936,-0.278046,-0.131870,-0.424223